<?php
$sql_code = "
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ( 'opt_about_desc_wp-pizza', 'Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_admin_email_wp-pizza', 'admin@yourdomain.com', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ( 'opt_blog_desc_wp-pizza', 'Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ( 'opt_blog_heading_wp-pizza', 'RECENT FROM BLOG', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ( 'opt_blog_home_status_wp-pizza', '0', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_facebook_lnk_wp-pizza', '#', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ( 'opt_ico_img_id_wp-pizza', '87', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_insta_lnk_wp-pizza', '#', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_logo_img_id_wp-pizza', '8', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ( 'opt_menu_desc_wp-pizza', 'Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ( 'opt_menu_heading_wp-pizza', 'Our menu pricing', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ( 'opt_menu_list_status_wp-pizza', '1', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_open_from_wp-pizza', 'Monday-Friday', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_org_address_wp-pizza', '198 West 21th Street Suite 721 New York NY 10016', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ( 'opt_org_loc_no_wp-pizza', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3025.306202756777!2d-74.04668908505792!3d40.68925344694453!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c25090129c363d0x40c6a5770d25022b!2sStatueofLibertyNationalMonument!5e0!3m2!1sen!2sin!4v1624018734560!5m2!1sen!2sin', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ( 'opt_phone_no_pain_plain_wp-pizza', '234-456-7890', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_phone_no_wp-pizza', '(+1) 234-456-7890', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ( 'opt_popular_desc_wp-pizza', 'Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ( 'opt_popular_heading_wp-pizza', 'HOT PIZZA MEALS', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ( 'opt_popular_sect_status_wp-pizza', '1', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_service_h1_1_wp-pizza', 'HEALTHY FOODS', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_service_h1_2_wp-pizza', 'FASTEST DELIVERY', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_service_h1_3_wp-pizza', 'ORIGINAL RECEIPES', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_service_icon_1_wp-pizza', 'flaticon-diet', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_service_icon_2_wp-pizza', 'flaticon-bicycle', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_service_icon_3_wp-pizza', 'flaticon-pizza-1', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_service_s1_1_wp-pizza', 'Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_service_s1_2_wp-pizza', 'Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_service_s1_3_wp-pizza', 'Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ( 'opt_service_status_wp-pizza', '1', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_service_topic_heading_wp-pizza', 'Our Services', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_service_topic_sub_heading_wp-pizza', 'Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ( 'opt_shop_img_id_1_wp-pizza', '82', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ( 'opt_shop_img_id_2_wp-pizza', '83', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ( 'opt_shop_img_id_3_wp-pizza', '84', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ( 'opt_shop_img_id_4_wp-pizza', '85', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ( 'opt_shop_img_status_wp-pizza', '1', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_site_email_wp-pizza', 'info@yourdomain.com', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_site_name_wp-pizza', 'Pizza World', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_slider_desc_1_wp-pizza', 'A small river named Duden flows by their place and supplies it with the necessary regelialia.', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_slider_desc_2_wp-pizza', 'A small river named Duden flows by their place and supplies it with the necessary regelialia.', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_slider_desc_3_wp-pizza', 'A small river named Duden flows by their place and supplies it with the necessary regelialia.', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_slider_heading_1_wp-pizza', 'Welcome', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_slider_heading_2_wp-pizza', 'Delicious', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_slider_heading_3_wp-pizza', 'Crunchy', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_slider_id_1_wp-pizza', '12', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_slider_id_2_wp-pizza', '10', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_slider_id_3_wp-pizza', '11', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_slider_redirect_1_wp-pizza', '', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_slider_redirect_2_wp-pizza', '#', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_slider_redirect_3_wp-pizza', '#', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ( 'opt_slider_status_wp-pizza', '1', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_slider_sub_heading_1_wp-pizza', 'We cooked your desired Pizza Recipe', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_slider_sub_heading_2_wp-pizza', 'Italian Pizza', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_slider_sub_heading_3_wp-pizza', 'Italian Cuizine', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ( 'opt_stat_1_count_wp-pizza', '100', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ( 'opt_stat_1_icon_wp-pizza', 'flaticon-pizza-1', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ( 'opt_stat_1_name_wp-pizza', 'Pizza Branches', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ( 'opt_stat_2_count_wp-pizza', '85', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ( 'opt_stat_2_icon_wp-pizza', 'flaticon-medal', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ( 'opt_stat_2_name_wp-pizza', 'Number of Awards', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ( 'opt_stat_3_count_wp-pizza', '10564', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ( 'opt_stat_3_icon_wp-pizza', 'flaticon-laugh', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ( 'opt_stat_3_name_wp-pizza', 'Happy Customer', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ( 'opt_stat_4_count_wp-pizza', '900', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ( 'opt_stat_4_icon_wp-pizza', 'flaticon-chef', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ( 'opt_stat_4_name_wp-pizza', 'Staff', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_text_logo_wp-pizza', 'Pizza World', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_timing_desc_wp-pizza', 'We are available 24/7, Dial Now', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_timing_from_wp-pizza', '8:00am - 9:00pm', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_twitter_lnk_wp-pizza', '#', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_welcome_desc_wp-pizza', 'On her way she met a copy. The copy warned the Little Blind Text, that where it came from it would have been rewritten a thousand times and everything that was left from its origin would be the word and and the Little Blind Text should turn around and return to its own, safe country. But nothing the copy said could convince her and so it didn’t take long until a few insidious Copy Writers ambushed her, made her drunk with Longe and Parole and dragged her into their agency, where they abused her for their.', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_welcome_heading_wp-pizza', 'Welcome to pizza world restuarant', 'yes');
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('opt_welcome_img_id_wp-pizza', '13', 'yes');
";